# ESPHome configuration for Kamstrup Multical 21 Water Meter Reader
# Uses CC1101 radio module to receive wM-Bus Mode C1 transmissions
# Standard ESP32 variant
#
# Hardware connections for Standard ESP32:
#   CC1101 VCC  -> 3V3
#   CC1101 GND  -> GND
#   CC1101 CSN  -> GPIO 4
#   CC1101 MOSI -> GPIO 23
#   CC1101 MISO -> GPIO 19
#   CC1101 SCK  -> GPIO 18
#   CC1101 GDO0 -> GPIO 32

substitutions:
  device_name: watermeter
  friendly_name: "Water Meter"
  # Get meter_id from the sticker on your meter (8 hex chars)
  meter_id: !secret multical21_meter_id
  # Get encryption key from your water provider (32 hex chars)
  meter_key: !secret multical21_meter_key

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600
    then:
      - logger.log:
          level: INFO
          tag: "boot"
          format: "\n\n\
            _______________________________________________________________\n\
            \n\
            \x20 __    __  __  __  __   ______  ____  ___    __    __     ___  __\n\
            \x20|  \\  /  ||  ||  ||  | |      ||    ||   \\  /  \\  |  |   |__ ||  |\n\
            \x20|   \\/   ||  ||  ||  |   ||   ||    ||    |/    \\ |  |      / |  |\n\
            \x20|        ||  ||  ||  |   ||   ||    ||    /  /\\  \\|  |     /  |__|\n\
            \x20|  |\\/|  ||  ||  ||  |   ||   ||    ||   |  /__\\  |  |    /   ____\n\
            \x20|  |  |  ||__||__||__|   ||   ||____||   | /    \\ |  |__ /__ |____|\n\
            \n\
            \x20              .---.                  _______\n\
            \x20             /     \\                |  .-.  |\n\
            \x20       ~~~~~~|     |~~~~~~          | |   | |\n\
            \x20      (   )  |  W  |  (   )         | | O |=+===\n\
            \x20       ~~~   | m3  |   ~~~          | |   | |   |\n\
            \x20             |_____|                |__|__|_|   |\n\
            \x20                                        \\   o  |\n\
            \x20      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~       \\ o   |\n\
            \x20      ============================--------'o---'\n\
            \n\
            \x20            << wM-Bus Mode C1 @ 868.95 MHz >>\n\
            \x20              Kamstrup Water Meter Reader\n\
            _______________________________________________________________\n\n"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: !secret ap_password

captive_portal:

# Status LED
status_led:
  pin: GPIO2

# SPI bus for CC1101
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# External custom components
external_components:
  - source: github://petterl/esp32-multical21@master
    components: [multical21]

# Multical21 water meter sensor
multical21:
  id: water_meter
  cs_pin: GPIO4
  gdo0_pin: GPIO32
  meter_id: ${meter_id}
  key: ${meter_key}

sensor:
  # Water meter sensors
  - platform: multical21
    multical21_id: water_meter
    total_consumption:
      name: "Total Water Consumption"
      icon: "mdi:water"
    month_start_value:
      name: "Month Start Value"
      icon: "mdi:calendar-month"
    water_temperature:
      name: "Water Temperature"
      icon: "mdi:thermometer-water"
    ambient_temperature:
      name: "Ambient Temperature"
      icon: "mdi:thermometer"
    current_flow:
      name: "Current Water Flow"
      icon: "mdi:water-pump"

  # WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Uptime sensor
  - platform: uptime
    name: "Uptime"

text_sensor:
  # Last update timestamp
  - platform: multical21
    multical21_id: water_meter
    last_update:
      name: "Last Update"
      icon: "mdi:clock-outline"

  # WiFi info
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"

binary_sensor:
  # Connection status
  - platform: status
    name: "Status"

button:
  # Restart button
  - platform: restart
    name: "Restart"
